security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        chain_provider:
            chain:
                providers: [db_email]
        db_email:
            entity:
                class: App\Entity\User
                property: email
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: chain_provider
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
            anonymous: true

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset_password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
