#!/bin/sh
# Esto se debe ejecutar en un cron cada 1 minuto
bin/console pull:ripio > /dev/null 2>&1
bin/console pull:binance > /dev/null 2>&1
bin/console pull:cryptomkt > /dev/null 2>&1
bin/console pull:buenbit > /dev/null 2>&1
bin/console pull:bitso > /dev/null 2>&1
bin/console arbitrar
