#!/bin/sh
# Esto se debe ejecutar en un cron cada 1 minuto
while :
do
    bin/console pull:ripio
    bin/console pull:binance
    bin/console pull:cryptomkt
    bin/console pull:buenbit
    bin/console pull:bitso
    echo Esperando...
    sleep 20
done
